# Generated by Django 5.2.7 on 2025-10-13 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.comment'),
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False, help_text='Highlight this post in listings'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.CharField(blank=True, help_text='Or provide an external image URL', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Web Development'), ('mobile', 'Mobile App'), ('desktop', 'Desktop App'), ('api', 'API Development'), ('other', 'Other')], default='web', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_link',
            field=models.URLField(blank=True, help_text='Live demo URL', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, help_text='Mark as a featured project'),
        ),
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, help_text='Link to source code repository', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.CharField(blank=True, help_text='Or provide an external image URL', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, help_text='Comma separated technologies', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell us about yourself'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='Where are you based?', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Optional phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, help_text='Share your portfolio or website'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('spam', 'Spam'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a featured image (optional)', null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='postview',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_records', to='core.post'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a project screenshot', null=True, upload_to='projects/'),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(blank=True, help_text='Internal path (e.g. /blog)', max_length=255)),
                ('external_url', models.URLField(blank=True, help_text='External URL if linking outside the site')),
                ('icon', models.CharField(blank=True, help_text='Bootstrap icon class, e.g. bi-house', max_length=50)),
                ('menu_type', models.CharField(choices=[('header', 'Header Menu'), ('footer', 'Footer Menu'), ('sidebar', 'Sidebar Menu')], default='header', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menu')),
            ],
            options={
                'ordering': ['menu_type', 'order', 'title'],
            },
        ),
    ]
